### PR TITLE
Upgrade PyYaml to 5.1

### PR DESCRIPTION
**Pull request by jfuss**
*Issue #, if available:*
N/A

*Description of changes:*
SAM CLI is looking to upgrade its dependencies, one of which is pyyaml. SAM CLI is blocked until this repo is also upgraded.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jfuss** [comment]
Flake8 is failing but doesn't appear to be anything I specifically did.

**Comment by jfuss** [comment]
Looks like there was a breaking change in pydocstyle in 4.0 and flake8-docstrings only requires a min 2.5 or greater (including major version bumps). Pinning pydocstyle to 3.0.0 in the Pipfile should solve this

**Comment by jfuss** [comment]
3.6 and 3.7 still fail though. Not really sure why pipenv keeps installing the broken version even if the Pipfile pins.

**Comment by jfuss** [comment]
Ping. Not sure why pipenv is being difficult here in some versions and not sure how to solve it.

**Comment by paoptu023** [comment]
Can you try changing the pinged pydocstyle version to be `pydcosteyle<4.0.0`? I found this post based on the build error message: https://github.com/PyCQA/pydocstyle/issues/375.

**Comment by jfuss** [comment]
@paoptu023 I tried that initially, pipenv kept installing 4.0 (no idea why). Considering pinning to 3.0, still installs 4.0 in only 2 versions, I am not sure what else to do here.

**Comment by jfuss** [comment]
The setup.py defined dev Extras, which we getting installed under the package section in the Pipfile. This will override any dependencies in the dev packages settings. Since extras and dev packages were the same, I removed the dev extras from the setup.py.

But that didn't seem to fix 3.6 or 3.7, so... something in travis is messing with things???

**Pull request merged**
